spring:
    application:
        name: Spring-boot-project
    datasource:
        password: Dang972004@
        url: jdbc:mysql://localhost:3306/demo_db
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: rnsmddbxngmybmat
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: danghoangtest1@gmail.com

    data:
        redis:
            host: localhost
            port: 6379
